/* cub-data.js
   Arquivo de dados do CUB - fonte unica de valores para todos os visitantes do site.
   Para atualizar: use o gerador (gerador-cub.html), baixe o novo arquivo e substitua
   este mesmo arquivo (cub-data.js) no repositorio do GitHub.
*/
window.CUB_DATA = {
  "config": {
    "ref": "",
    "cub1_2": 2865.74,
    "cub3": 3424.89,
    "cub4mais": 4178.31,
    "cubComercial": 2775.95,
    "cubMultifamiliar": 2466.71,
    "cubGalpao": 1564.27,
    "cubMulta607Res": 3151.24,
    "cubMulta607NaoRes": 3353.7,
    "pctEmpreitada": 48.85,
    "pctISS": 3,
    "pctDemolicao": 10,
    "alturaMuro": 1.2,
    "cubHistory": [
      {
        "id": "2022-01",
        "mes": "1",
        "ano": 2022,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2022-02",
        "mes": "2",
        "ano": 2022,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2022-03",
        "mes": "3",
        "ano": 2022,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2022-04",
        "mes": "4",
        "ano": 2022,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2022-05",
        "mes": "5",
        "ano": 2022,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2022-06",
        "mes": "6",
        "ano": 2022,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2022-07",
        "mes": "7",
        "ano": 2022,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2022-08",
        "mes": "8",
        "ano": 2022,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2022-09",
        "mes": "9",
        "ano": 2022,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2022-10",
        "mes": "10",
        "ano": 2022,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2022-11",
        "mes": "11",
        "ano": 2022,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2022-12",
        "mes": "12",
        "ano": 2022,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2023-01",
        "mes": "1",
        "ano": 2023,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2023-02",
        "mes": "2",
        "ano": 2023,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2023-03",
        "mes": "3",
        "ano": 2023,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2023-04",
        "mes": "4",
        "ano": 2023,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2023-05",
        "mes": "5",
        "ano": 2023,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2023-06",
        "mes": "6",
        "ano": 2023,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2023-07",
        "mes": "7",
        "ano": 2023,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2023-08",
        "mes": "8",
        "ano": 2023,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2023-09",
        "mes": "9",
        "ano": 2023,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2023-10",
        "mes": "10",
        "ano": 2023,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2023-11",
        "mes": "11",
        "ano": 2023,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2023-12",
        "mes": "12",
        "ano": 2023,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2024-01",
        "mes": "1",
        "ano": 2024,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2024-02",
        "mes": "2",
        "ano": 2024,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2024-03",
        "mes": "3",
        "ano": 2024,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2024-04",
        "mes": "4",
        "ano": 2024,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2024-05",
        "mes": "5",
        "ano": 2024,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2024-06",
        "mes": "6",
        "ano": 2024,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2024-07",
        "mes": "7",
        "ano": 2024,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2024-08",
        "mes": "8",
        "ano": 2024,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2024-09",
        "mes": "9",
        "ano": 2024,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2024-10",
        "mes": "10",
        "ano": 2024,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2024-11",
        "mes": "11",
        "ano": 2024,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2024-12",
        "mes": "12",
        "ano": 2024,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2025-01",
        "mes": "1",
        "ano": 2025,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2025-02",
        "mes": "2",
        "ano": 2025,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2025-03",
        "mes": "3",
        "ano": 2025,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2025-04",
        "mes": "4",
        "ano": 2025,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2025-05",
        "mes": "5",
        "ano": 2025,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2025-06",
        "mes": "6",
        "ano": 2025,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2025-07",
        "mes": "7",
        "ano": 2025,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2025-08",
        "mes": "8",
        "ano": 2025,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2025-09",
        "mes": "9",
        "ano": 2025,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2025-10",
        "mes": "10",
        "ano": 2025,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2025-11",
        "mes": "11",
        "ano": 2025,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2025-12",
        "mes": "12",
        "ano": 2025,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2026-01",
        "mes": "1",
        "ano": 2026,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2026-02",
        "mes": "2",
        "ano": 2026,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2026-03",
        "mes": "3",
        "ano": 2026,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2026-04",
        "mes": "4",
        "ano": 2026,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2026-05",
        "mes": "5",
        "ano": 2026,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2026-06",
        "mes": "6",
        "ano": 2026,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2026-07",
        "mes": "7",
        "ano": 2026,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      },
      {
        "id": "2026-08",
        "mes": "8",
        "ano": 2026,
        "cub1_2": 0,
        "cub3": 0,
        "cub4mais": 0,
        "cubComercial": 0,
        "cubMultifamiliar": 0,
        "cubGalpao": 0
      }
    ]
  },
  "pwHash": "00d4f1d6da3ff115422e7b5fb46b28fd8493e1a6b5883c463ca9a70f9bb992bd"
};
